---
- name: variables DEMO
  hosts: n6
  become: yes
  vars:
    myusername: Assawti

  tasks:
  - name: update dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html

...
